### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by songrotek** [carpedm20/NAF-tensorflow#1]
i got this error:
`Traceback (most recent call last):
  File "main.py", line 77, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 72, in main
    conf.max_step, conf.max_update, conf.max_episode, conf.test_step)
  File "/Users/FloodSurge/DeepReinforcementLearning/gymCodes/NAF-tensorflow-master/src/naf.py", line 57, in __init__
    name='pred_network', **shared_args
  File "/Users/FloodSurge/DeepReinforcementLearning/gymCodes/NAF-tensorflow-master/src/network.py", line 108, in __init__
    L = tf.transpose(tf.pack(rows, axis=1), (0, 2, 1))
TypeError: pack() got an unexpected keyword argument 'axis'`

The method is 
tf.pack(values, name='pack') 

I removed axis=1, still got errors.

**Comment by carpedm20** [comment]
You need to use nightly version of TensorFlow to use that function. I'll add version check for this error.

**Comment by songrotek** [comment]
Latest version from source?

**Comment by carpedm20** [comment]
Yes but you don't need to build it yourself. There's a link in README.md of TensorFlow repo.

**Comment by songrotek** [comment]
ok. Thank you for your quick response!

**Comment by songrotek** [comment]
i am testing it on my macbook, but it seems not work! The reward is always < -1000 how many episodes it need to converge to reward -130+?

**Comment by carpedm20** [comment]
You mean the episodic reward? Still, I'm working on different hyperparameters (maybe I should wrote a script for bruteforce search) and I don't think using same hyperparameters of the paper won't work for different domain of environment.

Also, author told me that gym and the environment used in the paper is different so I need to explore some experiments. But the reuslts of the screenshot in REAME can be achieved by <200 episodes.

I think normalizing the reward is necessary because it's range is too wide for Pendulum-v0.

**Comment by songrotek** [comment]
I am not very clear about the reward on tensorboard, it is different from the average reward on OpenAI gym evaluation. Do you have a plan to submit the result to OpenAI？

Since Pendulum is a simple environment, changing the reward is not a necessary step i think.  I tested DDPG on Pendulum-v0 without changing state,action range and reward, which achieved -240+-. But i failed to make DDPG work on Mujoco. it is still under experiment also.

**Comment by carpedm20** [comment]
@songrotek I've never seen the episodic reward before so now I checked and the current code can't achieve -240 for Pendulum. Hmm.. I'll figure out the reason why and I'll update statistics to draw stats per episode.

**Comment by carpedm20** [comment]
![pendulum-v0_2016-07-15](https://cloud.githubusercontent.com/assets/3346407/16844240/4aad2d34-4a1f-11e6-9727-fe5d33d5479b.png)

@songrotek now its working
