### ISSUE TITLE
README plot question

### ISSUE THREAD

**Issue by BarzinM** [carpedm20/NAF-tensorflow#4]
Hello, I was wondering what is the hyperparameter used for the blue line in the README plot (`assets/Pendulum-v0_2016-07-15.png`). Information for that plot line seems to be missing from the code block above it.

**Comment by carpedm20** [comment]
I used the default hyperparameters to get README.md plot. Is there something wrong?

**Comment by BarzinM** [comment]
Nothing wrong. From the results section in the README file, I can see what hyperparameters were used to generate different plot lines (i.e dark green, light green, yellow, green). There is a blue/purple looking line in the plot that I'm not sure what hyper parameters were used to generate that. I would appreciate your help with this. Thanks,

**Comment by carpedm20** [comment]
Oh, I see. So there is three green but no blue. Sorry but I don't remember which one but one of them should represent blue graph. I guess it's dark green or green which is 

    $ python main.py --env=Pendulum-v0 # dark green
    $ python main.py --env=Pendulum-v0 --use_seperate_networks=True # green

**Comment by BarzinM** [comment]
Thank you
